import { Currency } from '@prisma/client';

export interface ProductSeed {
  slug: string;
  category: string;
  name: string;
  emoji: string;
  rarity: string;
  currency: Currency;
  price: number;
  badge: string | null;
  stats: string[];
}

// Shop catalog — mirrors the frontend item list. Legendary items are priced in
// gems (premium currency, bought with real money); everything else in coins.
export const PRODUCTS: ProductSeed[] = [
  {
    slug: 'diamond-sword',
    category: 'Weapons',
    name: 'Diamond Sword',
    emoji: '⚔️',
    rarity: 'Rare',
    currency: Currency.COINS,
    price: 1200,
    badge: null,
    stats: ['Sharpness IV', 'Looting II', 'Unbreaking III'],
  },
  {
    slug: 'netherite-sword',
    category: 'Weapons',
    name: 'Netherite Sword',
    emoji: '🗡️',
    rarity: 'Legendary',
    currency: Currency.GEMS,
    price: 50,
    badge: 'HOT',
    stats: ['Sharpness V', 'Fire Aspect II', 'Looting III', 'Unbreaking III'],
  },
  {
    slug: 'power-bow',
    category: 'Weapons',
    name: 'Power Bow',
    emoji: '🏹',
    rarity: 'Epic',
    currency: Currency.COINS,
    price: 2500,
    badge: null,
    stats: ['Power V', 'Flame I', 'Infinity I', 'Punch II'],
  },
  {
    slug: 'iron-axe',
    category: 'Weapons',
    name: 'Iron Axe',
    emoji: '🪓',
    rarity: 'Common',
    currency: Currency.COINS,
    price: 300,
    badge: null,
    stats: ['Sharpness II', 'Unbreaking II'],
  },
  {
    slug: 'trident',
    category: 'Weapons',
    name: 'Trident',
    emoji: '🔱',
    rarity: 'Epic',
    currency: Currency.COINS,
    price: 3000,
    badge: 'NEW',
    stats: ['Riptide III', 'Loyalty II', 'Channeling I'],
  },
  {
    slug: 'crossbow',
    category: 'Weapons',
    name: 'Crossbow',
    emoji: '🎯',
    rarity: 'Uncommon',
    currency: Currency.COINS,
    price: 800,
    badge: null,
    stats: ['Multishot I', 'Quick Charge III', 'Unbreaking II'],
  },
  {
    slug: 'diamond-chestplate',
    category: 'Armor',
    name: 'Diamond Chestplate',
    emoji: '🛡️',
    rarity: 'Rare',
    currency: Currency.COINS,
    price: 1500,
    badge: null,
    stats: ['Protection IV', 'Unbreaking III'],
  },
  {
    slug: 'netherite-helmet',
    category: 'Armor',
    name: 'Netherite Helmet',
    emoji: '⛑️',
    rarity: 'Legendary',
    currency: Currency.GEMS,
    price: 30,
    badge: null,
    stats: ['Protection IV', 'Respiration III', 'Aqua Affinity I'],
  },
  {
    slug: 'elytra',
    category: 'Armor',
    name: 'Elytra',
    emoji: '🪽',
    rarity: 'Legendary',
    currency: Currency.GEMS,
    price: 60,
    badge: 'RARE',
    stats: ['Unbreaking III', 'Mending I', 'Pre-charged'],
  },
  {
    slug: 'leather-boots',
    category: 'Armor',
    name: 'Leather Boots',
    emoji: '👟',
    rarity: 'Common',
    currency: Currency.COINS,
    price: 200,
    badge: null,
    stats: ['Feather Falling II', 'Depth Strider I'],
  },
  {
    slug: 'iron-leggings',
    category: 'Armor',
    name: 'Iron Leggings',
    emoji: '🦵',
    rarity: 'Uncommon',
    currency: Currency.COINS,
    price: 700,
    badge: null,
    stats: ['Protection III', 'Unbreaking II'],
  },
  {
    slug: 'diamond-pickaxe',
    category: 'Tools',
    name: 'Diamond Pickaxe',
    emoji: '⛏️',
    rarity: 'Rare',
    currency: Currency.COINS,
    price: 1100,
    badge: null,
    stats: ['Fortune III', 'Efficiency V', 'Unbreaking III'],
  },
  {
    slug: 'netherite-pickaxe',
    category: 'Tools',
    name: 'Netherite Pickaxe',
    emoji: '⛏️',
    rarity: 'Legendary',
    currency: Currency.GEMS,
    price: 40,
    badge: 'BEST',
    stats: ['Efficiency V', 'Fortune III', 'Mending I', 'Unbreaking III'],
  },
  {
    slug: 'silk-touch-shovel',
    category: 'Tools',
    name: 'Silk Touch Shovel',
    emoji: '🪣',
    rarity: 'Uncommon',
    currency: Currency.COINS,
    price: 600,
    badge: null,
    stats: ['Silk Touch I', 'Efficiency IV'],
  },
  {
    slug: 'fishing-rod',
    category: 'Tools',
    name: 'Fishing Rod',
    emoji: '🎣',
    rarity: 'Uncommon',
    currency: Currency.COINS,
    price: 500,
    badge: null,
    stats: ['Luck of the Sea III', 'Lure III', 'Unbreaking II'],
  },
  {
    slug: 'flint-and-steel',
    category: 'Tools',
    name: 'Flint and Steel',
    emoji: '🔥',
    rarity: 'Common',
    currency: Currency.COINS,
    price: 150,
    badge: null,
    stats: ['Unbreaking II'],
  },
  {
    slug: 'diamond-bundle-x64',
    category: 'Resources',
    name: 'Diamond Bundle (x64)',
    emoji: '💎',
    rarity: 'Rare',
    currency: Currency.COINS,
    price: 900,
    badge: null,
    stats: ['64x Diamonds', 'Instant delivery'],
  },
  {
    slug: 'netherite-ingots-x4',
    category: 'Resources',
    name: 'Netherite Ingots (x4)',
    emoji: '🟫',
    rarity: 'Epic',
    currency: Currency.COINS,
    price: 2000,
    badge: 'VALUE',
    stats: ['4x Netherite Ingots', 'Bulk discount'],
  },
  {
    slug: 'iron-bundle-x256',
    category: 'Resources',
    name: 'Iron Bundle (x256)',
    emoji: '🔩',
    rarity: 'Common',
    currency: Currency.COINS,
    price: 250,
    badge: null,
    stats: ['256x Iron Ingots'],
  },
  {
    slug: 'obsidian-pack-x64',
    category: 'Resources',
    name: 'Obsidian Pack (x64)',
    emoji: '🖤',
    rarity: 'Uncommon',
    currency: Currency.COINS,
    price: 400,
    badge: null,
    stats: ['64x Obsidian', 'Perfect for bases'],
  },
  {
    slug: 'ancient-debris-x8',
    category: 'Resources',
    name: 'Ancient Debris (x8)',
    emoji: '🪨',
    rarity: 'Epic',
    currency: Currency.COINS,
    price: 1800,
    badge: null,
    stats: ['8x Ancient Debris', 'Nether origin'],
  },
  {
    slug: 'golden-apple-x16',
    category: 'Food',
    name: 'Golden Apple (x16)',
    emoji: '🍎',
    rarity: 'Rare',
    currency: Currency.COINS,
    price: 700,
    badge: null,
    stats: ['Regeneration II (5s)', 'Absorption I (2min)', '16x stack'],
  },
  {
    slug: 'enchanted-golden-apple',
    category: 'Food',
    name: 'Enchanted Golden Apple',
    emoji: '✨',
    rarity: 'Legendary',
    currency: Currency.GEMS,
    price: 35,
    badge: 'OP',
    stats: [
      'Regeneration II (20s)',
      'Absorption IV (2min)',
      'Fire Resistance (5min)',
    ],
  },
  {
    slug: 'steak-bundle-x64',
    category: 'Food',
    name: 'Steak Bundle (x64)',
    emoji: '🥩',
    rarity: 'Common',
    currency: Currency.COINS,
    price: 180,
    badge: null,
    stats: ['64x Cooked Beef', 'Restores 8 hunger'],
  },
  {
    slug: 'golden-carrot-x32',
    category: 'Food',
    name: 'Golden Carrot (x32)',
    emoji: '🥕',
    rarity: 'Uncommon',
    currency: Currency.COINS,
    price: 450,
    badge: null,
    stats: ['Best saturation food', 'Night Vision Potions base'],
  },
  {
    slug: 'bread-bundle-x32',
    category: 'Food',
    name: 'Bread Bundle (x32)',
    emoji: '🍞',
    rarity: 'Common',
    currency: Currency.COINS,
    price: 100,
    badge: null,
    stats: ['32x Bread', 'Easy to stack'],
  },
  {
    slug: 'strength-potion-ii',
    category: 'Potions',
    name: 'Strength Potion II',
    emoji: '💪',
    rarity: 'Uncommon',
    currency: Currency.COINS,
    price: 550,
    badge: null,
    stats: ['Strength II (1:30)', '3-pack included'],
  },
  {
    slug: 'invisibility-potion',
    category: 'Potions',
    name: 'Invisibility Potion',
    emoji: '👁️',
    rarity: 'Rare',
    currency: Currency.COINS,
    price: 950,
    badge: null,
    stats: ['Invisibility (3:00)', 'Perfect for PvP'],
  },
  {
    slug: 'healing-splash-pack',
    category: 'Potions',
    name: 'Healing Splash Pack',
    emoji: '🧪',
    rarity: 'Uncommon',
    currency: Currency.COINS,
    price: 600,
    badge: null,
    stats: ['Instant Health II', 'Splash type', '5-pack included'],
  },
  {
    slug: 'speed-potion-ii',
    category: 'Potions',
    name: 'Speed Potion II',
    emoji: '⚡',
    rarity: 'Common',
    currency: Currency.COINS,
    price: 300,
    badge: null,
    stats: ['Speed II (1:30)', '3-pack included'],
  },
  {
    slug: 'fire-resistance-potion',
    category: 'Potions',
    name: 'Fire Resistance Potion',
    emoji: '🔥',
    rarity: 'Uncommon',
    currency: Currency.COINS,
    price: 480,
    badge: null,
    stats: ['Fire Resistance (3:00)', 'Nether essential'],
  },
  {
    slug: 'night-vision-pack',
    category: 'Potions',
    name: 'Night Vision Pack',
    emoji: '🌙',
    rarity: 'Common',
    currency: Currency.COINS,
    price: 250,
    badge: null,
    stats: ['Night Vision (3:00)', '4-pack included'],
  },
];
